baseURL = "/"
title = "Gui Talarico"
theme = "hugo-coder"

googleAnalytics = "UA-3836052-1"

languageCode = "en-us"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "tango"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "gtalarico"

[params]
    author = "Gui Talarico"
    info = "Architecture : Design Technology : Software Engineering"
    description = "Gui Talarico's personal website"
    keywords = "developer,personal,python,revit api docs"
    avatarurl = "/img/avatar.jpg"

    favicon_32 = "/img/favicon.ico"
    favicon_16 = "/img/favicon.ico"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false
    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/gtalarico/"
[[params.social]]
    name = "Stackoverflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 2
    url = "https://stackoverflow.com/users/4411196/gtalarico?tab=profile"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/gtalarico/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://linkedin.com/in/gtalarico"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 5
    url = "https://instagram.com/gtalarico"
[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase fa-2x"
    weight = 6
    url = "https://keybase.io/gtalarico"


# Menu links
[[menu.main]]
    name = "Dev Projects"
    weight = 1
    url  = "/dev-projects/"
# [[menu.main]]
#     name = "Talks"
#     weight = 3
#     url  = "/talks/"
